on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Build and Push Docker Image to Docker Hub

jobs:
  get_package_version:
    name: get package version
    runs-on: ubuntu-latest
    container:
      image: nightio/shyaml:1.0.3
    steps:
      - uses: actions/checkout@v3
      - name: Get package version
        id: pk_version
        run: sh -c 'shyaml get-value Version < "DESCRIPTION"'

  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    needs: get_package_version
    steps:
      - name: check repository
        uses: actions/checkout@v4

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          file: inst/dockerfile/dockerfile
          push: true
          tags: odisce/spec2xtract:${{ needs.get_package_version.pk_version.outputs.stdout }}