on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Build and Push Docker Image to Docker Hub

env:
  DOCKER_REG: ${{secrets.DOCKERHUB_USERNAME}}

jobs:
  get_package_version:
    name: get package version
    runs-on: ubuntu-latest
    container:
      image: nightio/shyaml:1.0.3
    outputs:
      output1: ${{ steps.pk_version.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Get package version
        id: pk_version
        run: |
          PK_VERSION="$(sh -c 'shyaml get-value Version < "DESCRIPTION"')"
          PK_NAME="$(sh -c 'shyaml get-value Package < "DESCRIPTION"')"| tr '[:upper:]' '[:lower:]' 
          TAG="${DOCKER_REG}/${PK_NAME}:${PK_VERSION}"
          echo $TAG
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"
  # push_to_registry:
  #     name: push docker image to hub
  #     runs-on: ubuntu-latest
  #     needs: get_package_version
  #     steps:
  #       - name: check repository
  #         uses: actions/checkout@v4

  #       - name: login to docker registry
  #         uses: docker/login-action@v3
  #         with:
  #           username: ${{secrets.DOCKERHUB_USERNAME}}
  #           password: ${{secrets.DOCKERHUB_TOKEN}}

  #       - name: build and push docker image to registry
  #         uses: docker/build-push-action@v5
  #         with:
  #           file: inst/docker/dockerfile
  #           push: true
  #           tags: ${{ needs.get_package_version.outputs.output1 }}