on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Build and Push Docker Image to Docker Hub

env:
  REGISTRY: odisce
  IMAGE_NAME: spec2xtract

jobs:
  get_package_version:
    name: get package version
    runs-on: ubuntu-latest
    container:
      image: nightio/shyaml:1.0.3
    outputs:
      output1: ${{ steps.pk_version.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Get package version
        id: pk_version
        run: |
          PK_VERSION="$(sh -c 'shyaml get-value Version < "DESCRIPTION"')"
          echo "tag='odsice/spec2xtract:'${X}" >> "$GITHUB_OUTPUT"
  echo_version:
    name: paste version
    runs-on: ubuntu-latest
    needs: get_package_version
    steps:
      - name: echo package version
        run: echo ${{ needs.get_package_version.pk_version.outputs.output1 }}