on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Build and Push Docker Image to Docker Hub

env:
  REGISTRY: odisce
  IMAGE_NAME: spec2xtract

jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    needs: get_package_version
    steps:
      - name: check repository
        uses: actions/checkout@v4

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          file: inst/docker/dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}